[build]
target-dir = "target"

[target.'cfg(all())']
rustflags = [
  "-Dwarnings",
]

[alias]
t = "test --all-targets --all-features"
lint = "clippy --all-targets --all-features -- -D warnings"
fmtcheck = "fmt --all -- --check"